language: ruby

rvm:
  2.3.1

cache: bundler

# Adjust bundler argument to explicitly exclude this group
bunder_args: --without production

# Travis CI will execute the script
script: 'bundle exec rspec spec'